"""修改了用户的详情页模型

Revision ID: 0e18746fcd43
Revises: 4bada20df431
Create Date: 2023-12-06 13:18:51.445155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e18746fcd43'
down_revision = '4bada20df431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_class', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('original_class_manager', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('original_class_manager_mobile', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dormitory', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_mobile', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('class_student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('departure_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('competition_results', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('honors', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('honors')
        batch_op.drop_column('competition_results')
        batch_op.drop_column('departure_date')
        batch_op.drop_column('state')
        batch_op.drop_column('class_student_id')
        batch_op.drop_column('emergency_contact_mobile')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('dormitory')
        batch_op.drop_column('original_class_manager_mobile')
        batch_op.drop_column('original_class_manager')
        batch_op.drop_column('original_class')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
