"""加入了trainning_logs表

Revision ID: 9467fa694b55
Revises: 
Create Date: 2023-11-22 20:01:02.008235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9467fa694b55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), nullable=False),
    sa.Column('task', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_logs')
    # ### end Alembic commands ###
