"""修改了TrainingLogEvaluation的大小写的问题

Revision ID: da5f88a957aa
Revises: 0e18746fcd43
Create Date: 2023-12-06 14:11:48.611843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5f88a957aa'
down_revision = '0e18746fcd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_log_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=1024), nullable=True))
        batch_op.drop_column('Score')
        batch_op.drop_column('Comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_log_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Comment', sa.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column('Score', sa.INTEGER(), nullable=True))
        batch_op.drop_column('comment')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
